import bcrypt from 'bcryptjs';

const defaultPasswordHash = bcrypt.hashSync('password123', 10);

export const dbStore = {
  profiles: [
    { id: 'usr-1', name: 'Gowtham Seeker', email: 'user@example.com', role: 'user', phone: '+91 99999 88888', city: 'Hyderabad', language: 'English', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=gowtham' },
    { id: 'own-1', name: 'Satish Kumar', email: 'owner@example.com', role: 'owner', phone: '+91 98765 43210', city: 'Hyderabad', language: 'English', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=satish' },
    { id: 'own-2', name: 'Rahul Broker', email: 'pending@example.com', role: 'owner', phone: '+91 91234 56789', city: 'Bangalore', language: 'Hindi', email_verified: 1, verification_status: 'pending', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=rahul' },
    { id: 'adm-1', name: 'Admin Moderator', email: 'admin@example.com', role: 'admin', phone: '+91 90000 11111', city: 'Mumbai', language: 'English', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=admin' },
    { id: 'owner-2', name: 'Ramesh Rao', email: 'ramesh.rao@example.com', role: 'owner', phone: '+91 99887 76655', city: 'Hyderabad', language: 'Telugu', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=ramesh' },
    { id: 'owner-3', name: 'Priya Sharma', email: 'priya.s@example.com', role: 'owner', phone: '+91 91234 56789', city: 'Bangalore', language: 'English', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=priya' },
    { id: 'owner-4', name: 'Amit Patel', email: 'amit.p@example.com', role: 'owner', phone: '+91 93456 78901', city: 'Bangalore', language: 'Gujarati', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=amit' },
    { id: 'owner-5', name: 'Vikram Malhotra', email: 'vikram@example.com', role: 'owner', phone: '+91 98222 33333', city: 'Mumbai', language: 'English', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=vikram' },
    { id: 'owner-6', name: 'Sanjay Verma', email: 'sanjay.v@example.com', role: 'owner', phone: '+91 97777 88888', city: 'Delhi', language: 'Hindi', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=sanjay' },
    { id: 'owner-7', name: 'Anil Deshmukh', email: 'anil.d@example.com', role: 'owner', phone: '+91 94220 11223', city: 'Pune', language: 'Marathi', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=anil' },
    { id: 'owner-8', name: 'Karthik Raja', email: 'karthik.r@example.com', role: 'owner', phone: '+91 98400 12345', city: 'Chennai', language: 'Tamil', email_verified: 1, verification_status: 'verified', password_hash: defaultPasswordHash, avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=karthik' }
  ],

  properties: [
    {
      id: "prop-1",
      title: "Modern 2BHK Apartment near Metro",
      description: "Beautiful, well-ventilated 2BHK apartment situated on the 4th floor. Features a spacious living room, modern modular kitchen, and balconies with a city view. Located in a highly accessible area, just walking distance from the metro station. Excellent choice for families or working professionals.",
      purpose: "rent",
      property_type: "apartment",
      price: 22000,
      city: "Hyderabad",
      locality: "Ameerpet",
      latitude: 17.4375,
      longitude: 78.4482,
      bhk: 2,
      bathrooms: 2,
      area: 1100,
      furnishing: "semi-furnished",
      parking: 1,
      gym: 1,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "own-1",
      distance_to_metro: 300,
      nearby_metro_station: "Ameerpet Metro Station",
      distance_to_school: 500,
      nearby_school: "Hyderabad Public School",
      distance_to_hospital: 800,
      nearby_hospital: "Aster Prime Hospital",
      views: 342,
      favorites: 28,
      inquiries: 14,
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-2",
      title: "Premium 3BHK Villa with Private Garden",
      description: "Stunning 3BHK independent villa in a secure gated community. Comes with 2 covered car parkings, a private landscaped lawn, spacious terrace, and high-end Italian marble flooring. Proximity to major multispecialty hospitals makes it perfect for families seeking convenience and luxury.",
      purpose: "buy",
      property_type: "villa",
      price: 7800000,
      city: "Hyderabad",
      locality: "Kompally",
      latitude: 17.5348,
      longitude: 78.4805,
      bhk: 3,
      bathrooms: 3,
      area: 2400,
      furnishing: "furnished",
      parking: 1,
      gym: 0,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 0,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "owner-2",
      distance_to_metro: 4200,
      nearby_metro_station: "Miyapur Metro Station",
      distance_to_school: 1500,
      nearby_school: "Sherwood Public School",
      distance_to_hospital: 400,
      nearby_hospital: "Surekha Hospital & Diagnostics",
      views: 520,
      favorites: 42,
      inquiries: 19,
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-3",
      title: "Pet-Friendly 2BHK Near Tech Park",
      description: "Modern, pet-friendly 2BHK apartment situated in the heart of Whitefield's IT corridor. Equipped with high-speed internet connectivity potential, dedicated gym access, power backup, and intercom facilities. Highly recommended for couples and tech workers.",
      purpose: "rent",
      property_type: "apartment",
      price: 28000,
      city: "Bangalore",
      locality: "Whitefield",
      latitude: 12.9698,
      longitude: 77.7500,
      bhk: 2,
      bathrooms: 2,
      area: 1200,
      furnishing: "semi-furnished",
      parking: 1,
      gym: 1,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "owner-3",
      distance_to_metro: 800,
      nearby_metro_station: "Whitefield Kadugodi Metro",
      distance_to_school: 1100,
      nearby_school: "The Vydehi School",
      distance_to_hospital: 600,
      nearby_hospital: "Vydehi Hospital",
      views: 450,
      favorites: 37,
      inquiries: 22,
      images: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-4",
      title: "1BHK Cozy Flat for Rent",
      description: "Compact and affordable 1BHK builder floor flat, ideal for bachelors or students. Safe neighborhood, regular water supply, and easy connectivity to supermarkets and food courts. Located very close to public transportation networks.",
      purpose: "rent",
      property_type: "builder_floor",
      price: 14000,
      city: "Bangalore",
      locality: "HSR Layout",
      latitude: 12.9141,
      longitude: 77.6411,
      bhk: 1,
      bathrooms: 1,
      area: 600,
      furnishing: "unfurnished",
      parking: 0,
      gym: 0,
      balcony: 0,
      pet_friendly: 0,
      gated_community: 0,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 0,
      verified_property: 1,
      owner_id: "owner-4",
      distance_to_metro: 1800,
      nearby_metro_station: "HSR Layout Metro Station (Proposed)",
      distance_to_school: 400,
      nearby_school: "NIFT School Ground",
      distance_to_hospital: 700,
      nearby_hospital: "Narayana Multispeciality Hospital",
      views: 189,
      favorites: 12,
      inquiries: 8,
      images: [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-5",
      title: "Luxury 4BHK Penthouse with Sea View",
      description: "Exceptional double-height ceiling 4BHK penthouse in South Mumbai. Offers breathtaking panoramic ocean views, private splash pool, automation systems, 24/7 concierge, state-of-the-art gymnasium, and massive spacing. Fully verified and ready for possession.",
      purpose: "buy",
      property_type: "apartment",
      price: 45000000,
      city: "Mumbai",
      locality: "Bandra",
      latitude: 19.0596,
      longitude: 72.8295,
      bhk: 4,
      bathrooms: 4,
      area: 4200,
      furnishing: "furnished",
      parking: 1,
      gym: 1,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 0,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "owner-5",
      distance_to_metro: 1200,
      nearby_metro_station: "Bandra Metro Station",
      distance_to_school: 800,
      nearby_school: "Bandra St. Stanislaus High School",
      distance_to_hospital: 1100,
      nearby_hospital: "Lilavati Hospital",
      views: 890,
      favorites: 76,
      inquiries: 31,
      images: [
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-6",
      title: "Spacious 3BHK Flat near Metro Station",
      description: "Semi-furnished 3BHK flat located in a quiet lane of Dwarka. Just 200 meters from the metro station. Excellent connectivity to IGI airport. Features 3 bedrooms, 3 bathrooms, large balconies, modular kitchen, and standard security services.",
      purpose: "rent",
      property_type: "apartment",
      price: 32000,
      city: "Delhi",
      locality: "Dwarka Sector 12",
      latitude: 28.5925,
      longitude: 77.0425,
      bhk: 3,
      bathrooms: 3,
      area: 1650,
      furnishing: "semi-furnished",
      parking: 1,
      gym: 0,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 1,
      verified_property: 0,
      owner_id: "owner-6",
      distance_to_metro: 200,
      nearby_metro_station: "Dwarka Sector 12 Metro",
      distance_to_school: 900,
      nearby_school: "Mount Carmel School",
      distance_to_hospital: 1500,
      nearby_hospital: "Manipal Hospital Dwarka",
      views: 310,
      favorites: 22,
      inquiries: 11,
      images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-7",
      title: "Premium 2BHK Apartment in Gated Complex",
      description: "Strategically located 2BHK apartment in Kharadi, Pune, very close to EON IT Park. Rent includes maintenance charges. The community provides premium amenities including a fully functional gym, swimming pool, clubhouse, jogging track, and multi-tier security systems.",
      purpose: "rent",
      property_type: "apartment",
      price: 24500,
      city: "Pune",
      locality: "Kharadi",
      latitude: 18.5524,
      longitude: 73.9431,
      bhk: 2,
      bathrooms: 2,
      area: 1050,
      furnishing: "semi-furnished",
      parking: 1,
      gym: 1,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 1,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "owner-7",
      distance_to_metro: 3500,
      nearby_metro_station: "Kalyani Nagar Metro Station",
      distance_to_school: 400,
      nearby_school: "Kharadi Public School",
      distance_to_hospital: 900,
      nearby_hospital: "Columbia Asia Hospital",
      views: 408,
      favorites: 39,
      inquiries: 18,
      images: [
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80"
      ]
    },
    {
      id: "prop-8",
      title: "Elegant 3BHK House with Big Terrace",
      description: "An elegant, well-designed independent house in Adyar, Chennai. Features a huge open terrace, private parking space, a pooja room, and large windows. The house is pet-friendly and located in a very peaceful residential area with mature green tree linings.",
      purpose: "buy",
      property_type: "independent_house",
      price: 18500000,
      city: "Chennai",
      locality: "Adyar",
      latitude: 13.0033,
      longitude: 80.2550,
      bhk: 3,
      bathrooms: 3,
      area: 2100,
      furnishing: "unfurnished",
      parking: 1,
      gym: 0,
      balcony: 1,
      pet_friendly: 1,
      gated_community: 0,
      bachelor_friendly: 1,
      availability: "available",
      verified_owner: 1,
      verified_property: 1,
      owner_id: "owner-8",
      distance_to_metro: 1400,
      nearby_metro_station: "Kasturba Nagar MRTS Station",
      distance_to_school: 600,
      nearby_school: "St. Patrick's High School",
      distance_to_hospital: 700,
      nearby_hospital: "Fortis Malar Hospital",
      views: 295,
      favorites: 18,
      inquiries: 9,
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"
      ]
    }
  ],

  favorites: [],

  conversations: [
    {
      id: "convo-1",
      property_id: "prop-1",
      user_id: "usr-1",
      owner_id: "own-1"
    },
    {
      id: "convo-2",
      property_id: "prop-3",
      user_id: "usr-1",
      owner_id: "owner-3"
    }
  ],

  messages: [
    { id: "m-1", conversation_id: "convo-1", sender_id: "own-1", sender_role: "owner", text: "Hello! Thank you for showing interest in my property. When would you like to schedule a visit?", created_at: "2026-07-23T10:00:00Z" },
    { id: "m-2", conversation_id: "convo-2", sender_id: "usr-1", sender_role: "user", text: "Hi Priya, is this apartment available for immediate occupancy?", created_at: "2026-07-24T09:00:00Z" },
    { id: "m-3", conversation_id: "convo-2", sender_id: "owner-3", sender_role: "owner", text: "Yes, it is available from August 1st. We are currently accepting bookings.", created_at: "2026-07-24T09:05:00Z" }
  ],

  notifications: [
    { id: "notif-1", user_id: "usr-1", type: "system", title: "Welcome to HomeMatch AI", message: "Try our AI conversational search to find your dream property!", read: 0, created_at: "2026-07-24T06:00:00Z" },
    { id: "notif-2", user_id: "usr-1", type: "recommend", title: "New Match Identified!", message: "A new 2BHK apartment in Ameerpet is a 97% match for your search.", read: 0, created_at: "2026-07-24T08:30:00Z" },
    { id: "notif-3", user_id: "usr-1", type: "chat", title: "New Message from Satish", message: "When would you like to schedule a visit?", read: 0, created_at: "2026-07-24T10:01:00Z" }
  ],

  propertyVerifications: [
    { id: "v-prop-1-1", property_id: "prop-1", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-2-1", property_id: "prop-2", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-3-1", property_id: "prop-3", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-4-1", property_id: "prop-4", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-5-1", property_id: "prop-5", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-6-1", property_id: "prop-6", document_name: "Title Deed.pdf", status: "pending" },
    { id: "v-prop-7-1", property_id: "prop-7", document_name: "Title Deed.pdf", status: "verified" },
    { id: "v-prop-8-1", property_id: "prop-8", document_name: "Title Deed.pdf", status: "verified" }
  ]
};
